### ISSUE TITLE
is there any tutorial?

### ISSUE THREAD

**Issue by phsl-ofc** [Summaw/Text-Captcha-Solver#5]
is there any tutorial? I was looking for projects to solve these types of captchas and I fell into your projects, is there a tutorial or can you teach?

**Comment by Summaw** [comment]
No, I did not write a tutorial if you are running into installation problems you can look at previous opened issues and see what I responded there. I released the project because I don't have time to work on it anymore so no sorry I don't have time to teach you. You can read all about it though from a quick google search. If you run into a problem that hasn't previously been solved, please open another issue and I will try to help you when I have free time.
